<?php

namespace Wallabag\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PluginOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PluginOptionRepository extends EntityRepository
{
}
